deepspeed --num_gpus 4 --num_nodes 1 cli/train.py \
    --output_dir .cache/models \
    --init_ckpt /pretrained/llama-1b \
    --data_path /datasets/qi/ar/task065_timetravel_consistent_sentence_classification.train.jsonl \
    --max_seq_len 1024 \
    --train_steps 1000 \
    --eval_steps 10 \
    --save_steps 100 \
    --log_steps 1 \
    --pipe_parallel_size 1 \
    --model_parallel_size 1 \
    --use_flash_attn true \
    --deepspeed_config ./configs/llama.json