torchrun --nnodes 1 --nproc-per-node 1 --node_rank 0 cli/train.py \
    --output_dir /workspace/.cache/models \
    --init_ckpt /pretrained/tinyllama-2-1b-mp1 \
    --data_path /datasets/prompt.jsonl \
    --max_seq_len 1 \
    --train_steps 1000 \
    --eval_steps 10 \
    --save_steps 1000 \
    --log_steps 10 \
    --pipe_parallel_size 1 \
    --model_parallel_size 1 \
    --use_flash_attn true \
    --use_fused_ops true \
    --deepspeed_config ./configs/llama_lora.json