deepspeed --num_gpus 1 --num_nodes 1 cli/lora_train.py \
    --output_dir .cache/models \
    --init_ckpt .cache/ckpts/llama-2-7b-r2 \
    --data_path .cache/data/discourse_connective_identification.train.jsonl \
    --max_seq_len 1024 \
    --train_steps 1000 \
    --eval_steps 10 \
    --save_steps 100 \
    --log_steps 1 \
    --pipe_parallel_size 1 \
    --model_parallel_size 1 \
    --use_flash_attn true \
    --deepspeed_config ./configs/llama.json